.travis.yml
=> external pr test

README.md
=> Update readme to add install and https

CHANGELOG.md, src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue, src/wallets/bip44/ledgerPaths.js, src/wallets/hardware/ledger/index.js
=> add support for ledger live paths

package-lock.json, package.json
Update keepkey.js to fix passphrases.
=> Update keepkey.js to fix passphrases

package-lock.json, package.json
See: https://github.com/keepkey/keepkey.js/pull/8
=> Update keepkey.js to fix a concurrency issue

CHANGELOG.md, vue.config.js
=> set server side headers for develop

CHANGELOG.md, src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.scss, src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue, tests/unit/specs/src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.spec.js
- Fix send TX confirmation modal
=> Fix Send TX confirmation modal

src/wallets/bip44/ledgerPaths.js
=> Adds RSK ledger dpaths

src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
=> Turn addresses to lowercase to avoid issues with web3 in "Interact with contracts"

src/components/Notification/components/NotificationTypes/NotificationDetails/TransactionDetails.vue, src/components/Notification/components/NotificationTypes/TransactionNotification/TransactionNotification.vue
This should be updated when PR related to #809 is merged
=> Currency in notifications shown correctly

CHANGELOG.md, src/wallets/bip44/ledgerPaths.js
* Added ThunderCore to supported list of ledger derivations
* Ledger PR here: https://github.com/LedgerHQ/ledger-app-eth/pull/60
=> Add ledger support for ThunderCore

src/containers/ConfirmationContainer/components/AddressBlock/AddressBlock.vue
=> Shows the recipient and the contract address

CHANGELOG.md, src/containers/ConfirmationContainer/ConfirmationContainer.vue
=> fix no success modal showing after batch send

src/components/Notification/components/NotificationTypes/NotificationDetails/TransactionDetails.vue, src/components/Notification/components/NotificationTypes/TransactionNotification/TransactionNotification.vue, src/containers/ConfirmationContainer/ConfirmationContainer.vue, src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue, src/helpers/notificationFormatters/formatters.js, src/helpers/parseTokensData.js
With this changes, it will look like this:
=> Show token transfer data in notification body

CHANGELOG.md, src/builds/configs/base-routes.js, src/containers/FooterContainer/FooterContainer.vue, src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal-desktop.scss, src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue, src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal-desktop.scss, src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal.vue, src/layouts/HardwaresLayout/HardwaresLayout.vue
=> Update text and modal for hardware affiliates

src/networks/types/TOMO.js
TomoChain Explorer: https://scan.tomochain.com
=> Fix TomoChain Explorer link

.travis.yml
This will build the Travis CI job faster.
=> only clone the most recent commit

CHANGELOG.md, package.json, src/layouts/InterfaceLayout/InterfaceLayout.vue, src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue, src/wallets/web3-provider/providers/http-provider.js, src/wallets/web3-provider/providers/http-request-manager.js
=> Local Node Support

CHANGELOG.md, package-lock.json, package.json, src/helpers/index.js, src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue, src/layouts/AccessWalletLayout/components/PasswordModal/PasswordModal.vue, src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue, src/workers/wallet.worker.js
wallets for testing are attached, passwords are the filenames except for no-pass where password is empty
[mew-test-wallets.zip](https://github.com/MyEtherWallet/MyEtherWallet/files/3109896/mew-test-wallets.zip)
=> add presale and old mew wallet support

src/networks/types/TT.js, src/wallets/hardware/ledger/appPaths.js
* Add ThunderCore functionality to the ledger dropdown display
* Ledger PR: https://github.com/LedgerHQ/ledger-app-eth/pull/60
=> Add thundercore ledger support

.travis.yml, CHANGELOG.md
=> sync with exact timestamp

src/wallets/hardware/ledger/index.js
support 32bits chainId for Ledger hardware wallet.
without this PR, all networks with chainId > 255 do not work
- ~~[x] add all networks supported by Ledger (accidentally removed by 7ec9cd1dda41)~~
Please see https://github.com/kvhnuke/etherwallet/pull/1979
=> support 32bits chainId

src/wallets/hardware/keepkey/index.js
https://github.com/MyEtherWallet/MyEtherWallet/commit/d5d4764ae931b6a4062ddcffc86071a0233ac725#r34041005
=> keepkey: fix typo introduced in d5d4764ae

CHANGELOG.md, src/translations/errors-bitbox/en_US.json, src/translations/errors-bitbox/es_ES.json, src/translations/errors-bitbox/ja_JP.json, src/translations/errors-bitbox/ko_KR.json, src/translations/errors-bitbox/ru_RU.json, src/translations/errors-bitbox/zh_CN.json, src/translations/errors-bitbox/zh_TW.json, src/wallets/hardware/bitbox/digitalBitboxEth.js, src/wallets/hardware/bitbox/digitalBitboxUsb.js, src/wallets/hardware/bitbox/errorHandler.js, src/wallets/hardware/bitbox/index.js
---
This PR, in combination with a firmware update https://github.com/digitalbitbox/mcu/pull/283 fixes the BitBox communication error that started with Chrome 73 (which required also changes in Chrome that have since occurred).
We will release a new signed firmware in the next days that can be used to test this PR. If it helps, a live demo of this PR that works with BitBox hardware is also available at https://digitalbitbox.com/mew
This PR also fixes displaying correct error messages (in the red pop up boxes).
Thanks!
=> BitBox bugfixes: U2F communication; displaying error messages

src/dapps/MakerDai/MakerCDP.js
=> MakerDAO: fix withdraw ETH with infinite collateralization

CHANGELOG.md, README.md, src/layouts/CreateWalletLayout/components/ScanToDownloadModal/ScanToDownloadModal.scss
=> Fix UI: "Scan to Download" mobile UI update

CHANGELOG.md, README.md, src/containers/FaqsContainer/FaqsContainer.scss
- Update UI: frontpage FAQs content block
=> Update UI: frontpage FAQs content box

CHANGELOG.md, README.md, src/components/Notification/components/config.js, src/translations/confirmation/en_US.json
- Fix text translations "Succeed" to "Success"
=> Fix text translations

CHANGELOG.md, src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.scss, src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.vue
- Add hover effect to Dashboard -> Swap buttons
https://youtu.be/KIIAaOZiO4M
=> Add hovering effect to dashboard -> swap buttons

CHANGELOG.md, src/translations/interface/en_US.json, src/translations/interface/es_ES.json, src/translations/interface/ja_JP.json, src/translations/interface/ko_KR.json, src/translations/interface/ru_RU.json, src/translations/interface/zh_CN.json
- Add Changelly to Dashboard -> Swap description
=> Add Changelly to Dashboard -> Swap description

CHANGELOG.md, src/layouts/InterfaceLayout/components/InterfaceTokensModal/InterfaceTokensModal.scss, src/layouts/InterfaceLayout/components/InterfaceTokensModal/InterfaceTokensModal.vue
=> Update UI custom token modal

CHANGELOG.md, src/components/AddressQrcodeModal/AddressQrcodeModal.scss
- Update qrcode modal to be mobile friendly
=> Update address qrcode ui

CHANGELOG.md, package-lock.json, package.json, src/dapps/ManageENS/ManageENS.vue
=> ens subdomain fix

CHANGELOG.md, README.md
=> Add vulnerability reporting to readme

src/wallets/web3-provider/cx-web3-methods/eventHandler.js
=> Remove console

CHANGELOG.md, package-lock.json, src/assets/images/icons/HardwareWallet/xwallet.svg, src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue, src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.scss, src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.vue, src/layouts/AccessWalletLayout/components/XwalletModal/XwalletModal-desktop.scss, src/layouts/AccessWalletLayout/components/XwalletModal/XwalletModal-mobile.scss, src/layouts/AccessWalletLayout/components/XwalletModal/XwalletModal-tablet.scss, src/layouts/AccessWalletLayout/components/XwalletModal/XwalletModal.vue, src/layouts/AccessWalletLayout/components/XwalletModal/index.js, src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue, src/translations/access-wallet/en_US.json, src/translations/access-wallet/es_ES.json, src/translations/access-wallet/ja_JP.json, src/translations/access-wallet/ko_KR.json, src/translations/access-wallet/ru_RU.json, src/translations/access-wallet/zh_CN.json, src/translations/access-wallet/zh_TW.json, src/wallets/bip44/walletTypes.js
=> XWallet Integration 

CHANGELOG.md, src/containers/FooterContainer/FooterContainer.vue, src/translations/footer/en_US.json
=> Add mewconnect link

CHANGELOG.md, src/components/DropDownAddressSelector/DropDownAddressSelector.vue, src/dapps/Ambrpay/containers/SubscriptionForm/SubscriptionForm.vue, src/dapps/ScheduleTransaction/containers/ScheduleView.vue, src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue, src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue, src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapAddressSelector/SwapAddressSelector.vue, src/layouts/SendOfflineHelper/SendOfflineHelper.vue
=> Fix isValidAddress, merge clear n dropdown

src/wallets/bip44/keepkeyPaths.js
=> Add RSK dpath to Keepkey

src/containers/HeaderContainer/HeaderContainer.scss, src/containers/HeaderContainer/HeaderContainer.vue
- Remove Home link from main menu
- Replace down arrow for language menu
==============================================================
==============================================================
=> Remove Home link from main menu

CHANGELOG.md, package-lock.json, src/components/AddressBookModal/AddressBookModal.vue, src/components/DropDownAddressSelector/DropDownAddressSelector.vue, src/components/SettingsModal/SettingsModal.scss, src/components/SettingsModal/SettingsModal.vue
=> Update add book

CHANGELOG.md, src/containers/FooterContainer/FooterContainer-desktop.scss, src/containers/FooterContainer/FooterContainer-mobile.scss, src/containers/FooterContainer/FooterContainer-tablet.scss, src/containers/FooterContainer/FooterContainer.vue
- Fix padding and margin size for footer elements
=> Fix footer spacing

CHANGELOG.md, src/components/AddressBookModal/AddressBookModal.vue, src/components/DropDownAddressSelector/DropDownAddressSelector.vue, src/components/SettingsModal/SettingsModal.vue
=> Change to computed obj w translations

src/wallets/bip44/paths.js
bip44 path was wrong, sorry :(
=> Fix EtherCore Trezor address bug

src/components/DecisionTree/DecisionTree.vue
=> Fix quicklhelp translation

src/translations/create-wallet/en_US.json, src/translations/create-wallet/es_ES.json, src/translations/create-wallet/ja_JP.json, src/translations/create-wallet/ko_KR.json, src/translations/create-wallet/zh_CN.json
"Your have created your wallet successfully" has an extra r in the first word.
=> Fix your=>you typo

CHANGELOG.md, src/layouts/InterfaceLayout/containers/DashboardContainer/components/ButtonSendTx/ButtonSendTx.vue, src/translations/create-wallet/en_US.json, src/translations/create-wallet/es_ES.json, src/translations/create-wallet/ja_JP.json, src/translations/create-wallet/ko_KR.json, src/translations/create-wallet/zh_CN.json, src/translations/send-tx/en_US.json
=> Fix send tx translation

CHANGELOG.md, src/translations/mew-cx/en_US.json
=> Change translations

CHANGELOG.md, src/wallets/web3-provider/providers/ws-provider.js
=> remove keepalive net_version calls

CHANGELOG.md, package-lock.json, src/wallets/web3-provider/providers/ws-provider.js, src/wallets/web3-provider/providers/ws-web3-provider.js
=> devop/ws-reconnect [v5]

package-lock.json, package.json, src/layouts/AccessWalletLayout/AccessWalletLayout.vue, src/layouts/AccessWalletLayout/components/BitboxSelectModal/BitboxSelectModal.vue, src/wallets/hardware/bitbox02/index.js
Update bitbox api js to 0.4.0
Re-add lost bitbox modals
=> Bitbox02 integration fix

CHANGELOG.md, package-lock.json, src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/AdEx/AdEx.scss, src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/AdEx/AdEx.vue
=> adex width fix

CHANGELOG.md, package-lock.json, package.json, src/networks/nodes/ath.js, src/networks/nodes/ere.js, src/networks/types/ERE.js, vueConfig/connections.js
=> Package update

CHANGELOG.md, src/helpers/responseHandler/responseMatches.json, src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue, src/partners/dexAg/dexAg.js, src/partners/partners.js, src/translations/swap/en_US.json
=> add warning to change gas price

src/dapps/Unstoppable/containers/CompletedContainer/CompletedContainer.scss, src/dapps/Unstoppable/containers/CompletedContainer/CompletedContainer.vue, vueConfig/defaultConfigs.js
Add Unstoppable Domains tracking to credit myetherwallet affiliate for users that completed on order on MEW
=> Unstoppable Dapp: Add affiliate tracking

package-test.js
=> Exclude another package

.eslintrc.js, jest.config.js, package-lock.json, src/modules/name-resolver/helpers.js, src/modules/name-resolver/index.js, src/modules/name-resolver/resolvers/cns.js, src/modules/name-resolver/resolvers/ens.js, src/modules/name-resolver/tests/name-resolver.spec.js
=> devop: name-resolver module [v6]

CHANGELOG.md, package-lock.json, package.json, src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProvidersRadioSelector.vue, src/partners/dexAg/config/config.js, src/partners/dexAg/dexAg-calls.js, src/partners/dexAg/dexAg.js
- Remove restriction on dexes implemented when dexag was first integrated
=> remove prior restriction on dexes displayed when using dexag

CHANGELOG.md, package-lock.json, package.json
=> chore: update versions

CHANGELOG.md, src/dapps/GntMigrator/GntMigrator.vue
=> chore: fetch gnt values instead of relying on token list

package-test.js
=> exclude some packages for release

CHANGELOG.md, package-lock.json, package.json, src/dapps/Aave/containers/HomeContainer/HomeContainer.vue
=> revert aave container change

CHANGELOG.md, package-lock.json, src/components/DropDownAddressSelector/DropDownAddressSelector.scss, src/components/DropDownAddressSelector/DropDownAddressSelector.vue, src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftDetails/NftDetails.vue
* \[x] Link to issue: https://app.asana.com/0/inbox/1125971615701967
- Fix Send My CryptoKitties ui bug for Russian language
=> Fix Send My CryptoKitties UI issues for Russian language

package-test.js
=> exclude from update

package-lock.json, package.json
=> use older npm-force-resolutions

.github/workflows/add-to-v6-develop.yml, package-lock.json, package.json
this will let people test v6 develop at developv6.mewbuilds.com
=> devop: add workflow to set v6 develop domain

src/core/components/TheWrapperWallet.vue, src/views/layouts-wallet/TheDashboardLayout.vue, src/views/layouts-wallet/TheDeployContractLayout.vue, src/views/layouts-wallet/TheInteractContractLayout.vue, src/views/layouts-wallet/TheNFTManagerLayout.vue, src/views/layouts-wallet/TheSendTransactionLayout.vue
=> devop: rename TheLayoutWalletGrid to TheWrapperWallet

README.md
By making Getting started faster and simpler.
=> [README.md] Improve developer experience

README.md
- The version required was different than the one in package.json ("node": ">= 10.0.0 < 12.0.0")
- It wasn't obvious if version 8 is fine or at least 9 is required
=> [README.md] Fix version and make it more explicit

src/translations/access-wallet/en_US.json, src/translations/access-wallet/es_ES.json, src/translations/access-wallet/ja_JP.json, src/translations/access-wallet/ko_KR.json
I have never seen "...." after text, especially on a button.
=> Remove .... from Purchase a hardware wallet

CHANGELOG.md, package-lock.json, src/dapps/LendMigrator/LendMigrator.vue
=> devop: change the way we are checking lend balance

src/assets/images/networks/aqua.svg, src/networks/nodes/aqua-conical.js, src/networks/nodes/aqua-info.js, src/networks/nodes/index.js, src/networks/types/AQUA.js, src/networks/types/index.js, vueConfig/connections.js
adds aquachain network definition, svg image, and nodes
=> add aqua.js

package-lock.json, src/modules/address-book/components/AddressBookAddEdit.vue
=> build: prevent user from adding own address

src/wallets/bip44/paths.js, src/wallets/hardware/ledger/appPaths.js
* \[X ] Is this a user submitted bug?
* \[X ] Link to issue: #2896 
Corrects derivation paths for Avalanche C-Chain network
=> Correct Avalanche derivation paths

package-lock.json, package.json, src/modules/balance/ModuleBalanceCard.vue, src/modules/balance/components/BalanceAddressPaperWallet.vue
=> fix: checksum address and display correct info

package-lock.json, package.json, src/core/router/routes-default.js, src/views/components-default/TheDefaultFooter.vue, src/views/layouts-default/TheSecurityPolicyLayout.vue
=> devop: add security policy

CHANGELOG.md, package-lock.json, package.json
=> update package version

CHANGELOG.md, src/core/components/AppModal.vue
- Add scrollable option to app modal
https://user-images.githubusercontent.com/9893774/121436241-0e949400-c935-11eb-9218-6b67d38eefec.mp4
=> ui: add scrollable option to app modal

CHANGELOG.md, package-lock.json, src/core/components/AppPartnersBlock.vue, src/modules/create-wallet/components/CreateWalletMnemonicPhrase.vue, src/views/layouts-default/TheCreateWalletLayout.vue
* \[ ] Updated CHANGELOG.md
- Fix create wallet button paddings
- Fix create wallet Mnemonic update button
- Fix Mnemonic verification radio group UI bug
- Replace v-sheet with white-sheet to add box shadow style
=> V6/fix UI landing

src/views/components-default/HomeFeaturesDapps.vue
This implement new features dapps layot
ton the landing page
=> ui: add new ui for dapps features

CHANGELOG.md, devmoji.config.js, package-lock.json, package.json, src/modules/name-resolver/tests/name-resolver.spec.js, vue.config.js
=> fix: 🐛 sentry sourcemaps

src/views/layouts-default/TheBuyHardwareWalletLayout.vue
Update latest hardware wallet prices
=> ui: 🎨 get latest prices for hardware wallets

CHANGELOG.md, package-lock.json, src/modules/notifications/handlers/handlerNotification.mixin.js
=> devop: 🔧 add check if data exists 

CHANGELOG.md, src/modules/confirmation/ModuleConfirmation.vue
=> fix: 🐛 to addr when transferring tkn

package-lock.json, package.json
=> chore: 👷 update package

CHANGELOG.md, src/modules/decision-tree/components/MdContainer/MdContainer.vue
=> fix: 🐛 remove functional for now

CHANGELOG.md, package-lock.json, package.json, src/views/components-wallet/TheWalletFooter.vue
=> ui: 🎨 fix footer hiding content

CHANGELOG.md, package-lock.json, package.json, src/modules/notifications/ModuleNotifications.vue, src/modules/transfer-history/ModuleTransferHistory.vue
=> fix: 🐛 mew notification

CHANGELOG.md, package-lock.json, package.json, src/views/components-default/TheDefaultWalletBanner.vue
=> fix: 🐛 add scoped to wallet banner scss

CHANGELOG.md, package-lock.json, src/modules/swap/ModuleSwap.vue, src/modules/swap/handlers/configs/configTrendingTokens.js
https://app.asana.com/0/1163629870679883/1200627610509860
=> fix: 🐛 add swap to eth token

CHANGELOG.md, src/views/components-wallet/TheWalletFooter.vue
=> fix: 🐛 hide language select

CHANGELOG.md, package-lock.json, src/modules/settings/handler/gasPriceMixin.js, src/modules/swap/handlers/providers/changelly.js, src/modules/swap/handlers/providers/mew-provider-class.js, src/utils/networks/types/ETC.js, src/utils/networks/types/ETH.js, src/utils/networks/types/GOERLI.js, src/utils/networks/types/KOV.js, src/utils/networks/types/MATIC.js, src/utils/networks/types/RIN.js, src/utils/networks/types/ROP.js, src/views/TheWalletView.vue
=> fix: 🐛 polygon gas issue

CHANGELOG.md, package.json, src/app.vue, src/views/TheDefaultView.vue, src/views/TheWalletView.vue, src/views/components-default/TheDefaultHeader.vue, src/views/components-wallet/TheWalletHeader.vue
* \[x] Link to issue: 
- Move location of wallet header and make it static position
https://user-images.githubusercontent.com/9893774/126415281-a8f9b5f8-337f-4ce0-b567-05a45ac25c0f.mp4
=> fix: 🐛 wallet header overlapping issue on mobile

CHANGELOG.md, package-lock.json, package.json, src/modules/address-book/ModuleAddressBook.vue, src/modules/send/ModuleSend.vue, src/modules/swap/ModuleSwap.vue
=> feat: ✨ reset send and swap

CHANGELOG.md, package-lock.json, package.json, src/modules/confirmation/components/ConfirmationSwapTransactionDetails.vue
=> fix: 🐛 swap display value

CHANGELOG.md, package-lock.json, src/modules/access-wallet/ModuleAccessWalletHardware.vue
=> fix: 🐛 e.wallet undefiend error

CHANGELOG.md, package-lock.json, package-test.js
=> devop: 🔧 only require mew component updates when it's not in beta

CHANGELOG.md, src/modules/confirmation/components/ConfirmationSendTransactionDetails.vue
=> fix: 🐛 transaction confirmation total with fee

package.json, src/components/mew-tools/MewTools.vue
* \[x] Link to issue: https://app.asana.com/0/1125971615701970/1200663472522228
- fix main menu disappearing issue
https://user-images.githubusercontent.com/9893774/127065636-a339d0d8-9860-4d92-985e-97bf31b9dbfa.mp4
=> fix: 🐛 main menu disappearing issue

changelog/fix-3357.md, package-lock.json, package.json, src/core/helpers/sanitizeHex.js, src/modules/access-wallet/common/helpers.js, src/modules/access-wallet/common/utils.js
* \[x] Updated CHANGELOG
* \[x] sentry issue: TypeError sanitizeHex(src/modules/access-wallet/common/utils)
=> fix: 🐛 sanitize hex all the spots

changelog/fix-3370.md, package-lock.json, src/views/TheWalletView.vue
=> fix: 🐛 eip1559 basefee

changelog/fix-3378.md, package-lock.json, package.json, src/modules/contract/ModuleContractInteract.vue
=> fix: 🐛 hasEnough for contracts

CHANGELOG.md, changelog/fix-3373.md, package.json, src/core/components/TheWrapperWallet.vue, src/views/TheWalletView.vue
- fix wallet layout bug
- update paddings from 12px to 8px
https://app.asana.com/0/1125971615701970/1200742079762362
https://user-images.githubusercontent.com/9893774/128574994-d4873d33-69fd-4bba-af1d-602e89a743dd.mp4
https://user-images.githubusercontent.com/9893774/128799737-1bd3118b-f23e-4a07-8ec3-b92496555a53.mp4
=> fix: 🐛 wallet view layout bug

changelog/fix-3379.md, package-lock.json, package-test.js, src/dapps/staked-dapp/components/staked-stepper/StakedStepper.vue
=> fix: 🐛 add reset in staked steppers

changelog/fix-3380.md, package-test.js, src/modules/balance/handlers/handlerBalanceHistory.mixin.js
=> fix: 🐛 catch data error when balance is undefined on fetch

CHANGELOG.md, changelog/fix-3374.md, package.json, src/views/layouts-default/TheAccessWalletLayout.vue
- reduce side padding
https://app.asana.com/0/1125971615701970/1200742079762378
=> fix: 🐛 reduce access wallet side padding

changelog/ui-3405.md, src/modules/balance/components/PaperWalletToDisplay.vue
* \[x] Link to issue: https://app.asana.com/0/1163629870679883/1200803584653830
- Fix paperwallet qr code image
=> fix: 🐛  qr code image

changelog/fix-3412.md, package-lock.json, package.json, src/modules/access-wallet/hybrid/handlers/WalletLink/index.js, src/modules/toast/handler/handlerToast.js
=> fix: 🐛 wallet access issues

changelog/fix-3397.md, src/modules/access-wallet/hybrid/handlers/WalletConnect/errorHandler.js, src/modules/access-wallet/hybrid/handlers/WalletLink/errorHandler.js
=> fix: 🐛 setItem null error

changelog/fix-3424.md, package-lock.json, src/modules/access-wallet/hardware/handlers/hardwares/ledger/index.js, src/modules/confirmation/ModuleConfirmation.vue
=> fix: 🐛 ledger send

changelog/fix-3430.md, package-lock.json, package.json, src/modules/send/ModuleSend.vue, src/utils/web3-provider/methods/utils.js
=> fix: 🐛 invalid notifications

changelog/fix-3428.md, package.json, src/dapps/ens-manager-dapp/TheENSManagerLayout.vue, src/dapps/ens-manager-dapp/handlers/handlerENSManagerInterface.js
=> fix: 🐛 ens manager error

changelog/fix-3426.md, package.json, src/modules/confirmation/ModuleConfirmation.vue
=> fix: 🐛 metamask send tx

changelog/fix-3440.md, src/modules/swap/ModuleSwap.vue
=> fix: 🐛 check for token type and symbols

changelog/fix-3445.md, src/core/store/external/actions.js
=> fix: 🐛  token balance for non decimal

changelog/fix-3439.md, src/core/components/AppNetworkFee.vue, src/modules/network/ModuleNetwork.vue, src/modules/nft-manager/ModuleNftManager.vue, src/modules/settings/ModuleSettings.vue, src/views/components-wallet/TheWalletSideMenu.vue
=> fix: 🐛 rerouting on refresh

.github/workflows/remove-old-lokalise.yml, changelog/devop-3460.md, package.json, remove-old-lokalise-prs.js
=> devop: 🔧  github action to remove old lokalise branches

changelog/devop-3469.md, package-lock.json, src/core/store/global/actions.js
=> chore: 👷 silently fail matomo

package-test.js
=> chore: 👷 add packages to exclusion for now

CHANGELOG.md, package-lock.json, package.json, src/modules/swap/ModuleSwap.vue
* \[x] Link to release: https://github.com/MyEtherWallet/MyEtherWallet/releases/tag/v6.2.0-hotfix.1
=> release: 🔥 v6.2.0-hotfix.1

changelog/fix-3534.md, package-lock.json, src/app.vue, src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue, src/modules/access-wallet/software/components/AccessWalletMnemonic.vue, src/modules/address-book/ModuleAddressBook.vue, src/modules/address-book/components/AddressBookAddEdit.vue, src/modules/balance/components/TokenAddCustom.vue, src/modules/confirmation/ModuleConfirmation.vue, src/modules/swap/components/SwapProvidersList.vue
=> fix: 🐛 address book issue

package-test.js
=> fix: 🐛 exclude packages for release

.github/workflows/add-to-develop.yml, .github/workflows/add-to-mewbuilds.yml, .github/workflows/deploy-live.yml
=> fix: 🐛 pip issue

package-lock.json, package-test.js
=> chore: 👷 add package exclusion

.github/workflows/add-to-develop.yml, .github/workflows/add-to-mewbuilds.yml, .github/workflows/deploy-live.yml, changelog/fix-3548.md, package-lock.json, package.json, src/core/helpers/gasPriceHelper.js, src/dapps/ens-manager-dapp/handlers/handlerPermanentName.js, src/modules/access-wallet/common/helpers.js, src/modules/send/ModuleSend.vue
=> fix: :bug: ens and max amount

changelog/fix-3546.md, package-lock.json, package.json, src/modules/toast/handler/handlerToast.js
=> fix: 🐛 cancel metamask tx

changelog/fix-3547.md, package-lock.json, package.json, src/views/components-default/TheDefaultFooter.vue
=> fix: 👷 fix terms on mobile

.github/workflows/add-to-develop.yml, .github/workflows/add-to-mewbuilds.yml, .github/workflows/deploy-live.yml, changelog/fix-3545.md, package-lock.json, src/core/store/configs.js, src/core/store/custom/actions.js, src/core/store/custom/getters.js, src/core/store/custom/mutations.js, src/core/store/custom/state.js, src/core/store/global/actions.js, src/core/store/global/mutations.js, src/core/store/global/state.js, src/modules/access-wallet/hardware/components/AccessWalletDerivationPath.vue, src/modules/access-wallet/software/components/AccessWalletMnemonic.vue, src/modules/balance/components/TokenAddCustom.vue, src/modules/send/ModuleSend.vue
=> fix: 🐛 allow users to send custom tokens

changelog/fix-3552.md, package-lock.json, package-test.js, package.json, src/modules/swap/ModuleSwap.vue
* \[x] Link to release: https://github.com/MyEtherWallet/MyEtherWallet/releases/tag/v6.3.0-hotfix.1
=> chore: 👷 fix swap when sending with token

package-lock.json, package.json, src/core/store/wallet/actions.js, src/modules/access-wallet/common/helpers.js, src/modules/confirmation/ModuleConfirmation.vue, src/modules/confirmation/components/ConfirmationSwapTransactionDetails.vue
=> fix: 🐛 token to token swap

changelog/fix-3574.md, src/modules/access-wallet/hardware/handlers/hardwares/ledger/errorHandler.js, src/translations/errors-ledger/en_US.json
=> fix: 🐛 add in another ledger error

changelog/fix-3575.md, src/core/store/wallet/actions.js, src/utils/web3-provider/providers/ws-provider.js
=> fix: 🐛 add check for reading disconnects

README.md, changelog/feat-3572.md, src/app.vue
=> feat:  ✨ add in log message on app start

changelog/fix-3595.md, package-lock.json, package.json, src/modules/access-wallet/ModuleAccessWalletHardware.vue
=> fix: 🐛 bitbox access

changelog/devop-3611.md, changelog/fix-3608.md, src/modules/access-wallet/ModuleAccessWalletHardware.vue, src/modules/access-wallet/common/WalletErrorHandler.js, src/modules/access-wallet/hardware/components/AccessWalletBitbox.vue, src/modules/access-wallet/hardware/handlers/configs/configWallets.js, src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/errorHandler.js, src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/index.js, src/views/components-default/TheDefaultFooter.vue, src/views/layouts-default/TheBuyHardwareWalletLayout.vue
=>  devop: 🔧  bitbox02

changelog/fix-3613.md, src/modules/swap/ModuleSwapRates.vue
=> fix: 🐛 swap rates value not fetching for 1 ETH

changelog/fix-3615.md, package-lock.json, package.json, src/modules/balance/ModuleTokens.vue, src/modules/swap/ModuleSwap.vue
=> fix: 🐛 token swap on swap page

changelog/fix-3647.md, src/main.js
=> fix: 🐛 value setting for test mode

changelog/ui-3658.md, src/modules/balance/ModuleTokens.vue
=> fix: 🐛 Handle Text Overflow

changelog/devop-3659.md, src/core/components/AppNetworkSettingsModal.vue, src/modules/analytics-opt-in/handlers/configs/configCategories.js, src/modules/analytics-opt-in/handlers/handlerAnalytics.mixin.js
=> Devop: 🔧 Added Gas Switch Tracker

changelog/fix-3670.md, src/core/components/AppAddrQr.vue, src/translations/interface/en_US.json
=> fix: 🐛 bsc popup

changelog/fix-3666.md, package-lock.json, src/core/store/addressBook/state.js
=> fix: 🐛 refresh address book

CHANGELOG.md, package-audit.js, package-lock.json, package-test.js, package.json, src/dapps/DAPP_INTEGRATION.md
* \[x] Link to release: https://github.com/MyEtherWallet/MyEtherWallet/releases/tag/v6.4.5-hotfix.1
=> release: 🔥  v6.4.5-hotfix.1

changelog/chore-3679.md, package-test.js
=> chore: exclude packages

changelog/devop-3674.md, package-lock.json, src/modules/analytics-opt-in/handlers/configs/configCategories.js, src/modules/analytics-opt-in/handlers/handlerAnalytics.mixin.js, src/modules/global-modals/ModuleGlobalModals.vue
- https://app.asana.com/0/1125971615701970/1201781951680543
=> devop: add matomo global error tracking

changelog/devop-3698.md, package-lock.json, src/modules/confirmation/components/ConfirmationValuesContainer.vue, src/modules/swap/ModuleSwap.vue, src/modules/swap/components/SwapProvidersList.vue, src/modules/swap/handlers/providers/changelly.js
=> devop: 🔧 add correct prop for mew-token-container

changelog/fix-3702.md, package-lock.json, package.json, src/modules/balance/ModuleTokensValue.vue
- https://app.asana.com/0/1125971615701970/1201874294168654
- remove more button when the user has no tokens
=> devop: update packages

changelog/fix-3697.md, package-lock.json, package.json, src/core/store/global/actions.js, src/core/store/swap/actions.js, src/core/store/swap/mutations.js, src/modules/network/components/NetworkSwitch.vue, src/modules/swap/ModuleSwap.vue
=> fix: 🐛 fetch tokens when network switches

changelog/fix-3711.md, package-lock.json, src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
=> fix: 🐛 first mnemonic phrase error

changelog/devop-3723.md, src/modules/contract/ModuleContractInteract.vue
=> devop: 🔧 added check for contracts

changelog/fix-3715.md, src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/errorHandler.js
=> fix: 🐛 add bitbox error

changelog/fix-3732.md, package-lock.json, package-test.js, src/core/store/wallet/mutations.js, src/modules/address-book/ModuleAddressBook.vue, src/modules/confirmation/ModuleConfirmation.vue, src/modules/swap/ModuleSwap.vue, src/modules/swap/handlers/handlerSwap.js, src/modules/swap/handlers/providers/changelly.js, src/views/components-wallet/TheWalletSideMenu.vue
* \[x] Link to release: https://github.com/MyEtherWallet/MyEtherWallet/releases/tag/v6.4.8-hotfix.1
=> release: 🔥 v6.4.8-hotfix.1

CHANGELOG.md, package-lock.json, package-test.js, package.json, src/views/TheWalletView.vue
* \[x] Link to release:  https://github.com/MyEtherWallet/MyEtherWallet/releases/tag/v6.5.0-hotfix.1
* \[X] Updated package.json version
=> release: 🔥  v6.5.0-hotfix.1

changelog/fix-3756.md, src/modules/balance/ModuleBalance.vue, src/modules/send/ModuleSend.vue, src/modules/swap/ModuleSwap.vue, src/views/components-wallet/TheWalletHeader.vue
=> fix: 🐛 symbol search for from tokens, price for to tokens

changelog/fix-3778.md, src/utils/web3-provider/providers/ws-provider.js
=> fix: 🐛 websocket

connections.js, src/utils/networks/nodes/index.js, src/utils/networks/nodes/mintme-mew-ws.js, src/utils/networks/types/MINTME.js, src/utils/networks/types/index.js
Mintme network is not listed in the new MEW version 6, yet it's there on version 5. This PR contains ws configuration for the MINTME network.
=> Added MintMe websocket support 

changelog/fix-3824.md, src/modules/send/ModuleSend.vue
=> fix: 🐛 module send error null

changelog/fix-3869.md, src/main/errorHandler.js
=> fix: sentry internal json-rpc error

changelog/fix-3877.md, src/main/errorHandler.js
=> fix: sentry invalid argument

changelog/fix-3907.md, package-lock.json, package.json, src/core/helpers/localization.js, src/dapps/stakewise/store/getters.js, src/modules/access-wallet/ModuleAccessWalletHardware.vue, src/modules/access-wallet/hardware/handlers/hardwares/ledger/errorHandler.js, src/modules/access-wallet/hardware/handlers/hardwares/trezor/errorHandler.js
=> fix: 🐛 sentry fixes

changelog/fix-3936.md, package-lock.json, src/modules/address-book/ModuleAddressBook.vue
=> Sentry: ENS missing provider

changelog/sentry-3957.md, package-lock.json, package.json, src/modules/address-book/components/AddressBookAddEdit.vue, src/modules/moon-pay/components/MoonPayBuyComponent.vue, src/modules/swap/ModuleSwap.vue, src/modules/swap/components/SwapProvidersList.vue
=> Sentry: Properties undefined

changelog/fix-3958.md, package-lock.json, package.json, src/main/errorHandler.js
=> fix: 🐛 sentry gatt server disconnected err

changelog/ui-3965.md, src/modules/contract/ModuleContractInteract.vue
=> ui: 🎨 updated text

changelog/fix-3962.md, package-lock.json, src/core/store/external/actions.js
=> Sentry: invalid address

changelog/fix-3966.md, package-lock.json, src/modules/swap/components/SwapProvidersList.vue
=> Sentry: undefined property isActive

package-lock.json, package.json, src/modules/swap/ModuleSwap.vue
=> Fix: Swap page not loading

changelog/fix-4017.md, package-lock.json, package.json, src/modules/access-wallet/hardware/handlers/hardwares/ledger/errorHandler.js
=> fix: ledger usb transfer

changelog/fix-4045.md, package-lock.json, package.json, src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue, src/modules/access-wallet/software/handlers/mnemonic/index.js
=> Fix: Mnemonic phrase not loading

changelog/fix-4069.md, src/modules/create-wallet/components/CreateWalletMnemonicPhrase.vue
=> Fix: 🐛 Verify Extra Word

changelog/fix-4058.md, src/modules/moon-pay/components/MoonPayBuyComponent.vue
=> Fix: buy tooltip daily limit

changelog/fix-4063.md, package-test.js, src/modules/moon-pay/components/MoonPaySellComponent.vue
=> Fix: Moonpay sell dollar values

changelog/fix-4064.md, src/modules/swap/ModuleSwap.vue
=> Fix: Swap endless loading on token value change

changelog/fix-4068.md, src/views/layouts-default/TheAccessWalletLayout.vue
=> Fix: MetaMask login error message

changelog/fix-4070.md, src/modules/access-wallet/ModuleAccessWalletHardware.vue, src/views/layouts-default/TheAccessWalletLayout.vue
=> Fix: ledger access wallet back button

changelog/fix-4130.md, package-lock.json, package.json, src/modules/swap/handlers/handlerSwap.js
=> Sentry: check for baseList undefined

changelog/fix-4127.md, src/views/TheWalletView.vue
=> fix: Mnemonic Phrase network changing

changelog/fix-4135.md, fetchLists/lists/tokens.json, package-lock.json, package.json, src/modules/moon-pay/components/MoonPayBuyComponent.vue
=> Fix: moonpay undefined symbol

package-test.js
=> fix: 🐛 build

changelog/devop-4151.md, src/dapps/aave-dapp/handlers/handlerAave.mixin.js
=> devop: add matomo tracking to aave

changelog/fix-4153.md, package-lock.json, src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
=> Fix: mnemonic addressbook nickname error

changelog/fix-4155.md, src/modules/confirmation/handlers/errorHandler.js
=> devop: 🔧 added nonce message

changelog/fix-4165.md, package-lock.json, package.json, src/dapps/aave-dapp/metainfo.js
=> devop: update Aave subtitle

package-test.js, src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
=> chore: 👷 add analytics mixin in ens

changelog/fix-4128.md, src/core/mixins/enkryptMarketing.mixin.js, src/views/components-default/HomeLanding.vue
-  fix enkrypt button links and add mobile enkrypt buttons
=> fix: fix enkrypt button links and add mobile enkrypt buttons

changelog/fix-4184.md, package-test.js, package.json, src/dapps/ens-manager-dapp/components/reverse/EnsReverseLookup.vue
- remove ens-lookup dropdown icons
=> fix: remove ens-lookup dropdown icons

changelog/devop-4192.md, src/modules/analytics-opt-in/handlers/configs/configCategories.js, src/modules/analytics-opt-in/handlers/handlerAnalytics.mixin.js, src/modules/confirmation/ModuleConfirmation.vue, src/modules/swap/ModuleSwap.vue, src/views/components-wallet/TheWalletSideMenu.vue
=> devop: change matomo tracking swap

changelog/devop-4200.md, src/modules/confirmation/ModuleConfirmation.vue, src/modules/confirmation/components/SuccessModal.vue
=> Devop: 🔧 Hide x button

changelog/devop-4201.md, src/modules/swap/ModuleSwap.vue
=> Devop: 🔧 Added missing req message

changelog/devop-4220.md, src/modules/analytics-opt-in/handlers/configs/configCategories.js, src/modules/analytics-opt-in/handlers/handlerAnalytics.mixin.js, src/views/components-default/TheDefaultHeader.vue, src/views/components-wallet/TheWalletHeader.vue, src/views/components-wallet/TheWalletSideMenu.vue
=> devop: matomo buy sell

changelog/fix-4226.md, src/modules/message/ModuleMessageSign.vue
=> fix: 🐛 disable sign button

changelog/fix-4231.md, src/assets/images/networks/mintme.svg
- fix mint me token icon issue
=> fix: fix mint me token icon

changelog/fix-4224.md, src/modules/swap/ModuleSwap.vue
=> Sentry: Cannot read properties of undefined (reading 'contract')

changelog/devop-4244.md, package-lock.json, package.json, src/modules/balance/ModuleBalanceCard.vue, src/modules/balance/components/BalanceAddressPaperWallet.vue, tests/e2e/functions.js, tests/e2e/specs/print-wallet-test.js
=> devop: 🔧 printwallet e2e testing

CHANGELOG.md, package-lock.json, package-test.js, package.json, src/builds/mewcx/cxHelpers/background.js, src/builds/mewcx/cxHelpers/cxWeb3.js, src/layouts/ExtensionBrowserAction/components/CxHeader/CxHeader.vue, src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue, src/layouts/ExtensionPopup/ExtensionPopup.vue, src/layouts/ExtensionPopup/containers/AccountsContainer/AccountsContainer.vue, src/layouts/ExtensionPopup/containers/WelcomeContainer/WelcomeContainer.vue, src/translations/mew-cx/en_US.json
=> chore: add migration changes

CHANGELOG.md, package-lock.json, package.json, src/layouts/ExtensionBrowserAction/components/CxHeader/CxHeader.vue, src/layouts/ExtensionPopup/ExtensionPopup.vue
=> fix: my wallets

.github/workflows/add-offline-build-release-pr.yml, .github/workflows/run-on-pr.yml, CHANGELOG.md, package-lock.json, package.json
=> chore: 👷 update version

CHANGELOG.md, package-lock.json, package.json, src/builds/mewcx/cxHelpers/background.js
=> chore: only open enkrypt when updated

changelog/devop-4260.md, src/core/components/AppButtonBalance.vue, src/modules/swap/ModuleSwap.vue, src/views/components-wallet/TheWalletSideMenu.vue, tests/e2e/specs/eth-erc-swap-test.js
=> devop: 🔧 e2e test for swap eth to erc token

changelog/fix-4252.md, src/modules/balance/ModuleBalanceCard.vue
=> Sentry: null reading meta (ModuleBalanceCard)

changelog/fix-3818.md, package-lock.json, package.json, src/main/errorHandler.js
=> fix: 🐛 sentry nonce too low

changelog/fix-4079.md, src/modules/access-wallet/common/WalletInterface.js, src/modules/swap/handlers/providers/changelly.js, src/modules/swap/handlers/providers/mew-provider-class.js
=> fix: matic promise error handling

changelog/fix-3813.md, package-lock.json, src/modules/swap/handlers/providers/mew-provider-class.js
=> fix: 🐛 type error minmax minfrom

src/core/store/external/getters.js
=> revert: ⏪️ fetch main token:

changelog/fix-4307.md, package-lock.json, package.json, src/modules/notifications/helpers/formatNotification.js
=> Sentry: blockExplorerTX is undefined

changelog/fix-4314.md, package-audit.js, src/modules/balance/components/BalanceAddressPaperWallet.vue
=> fix: fix broken paperwallt layout

src/dapps/aave-dapp/components/AaveAmountForm.vue, src/dapps/aave-dapp/components/overlays/AaveRepayOverlay.vue
=> fix: 🐛 aave amount

CHANGELOG.md, connections.js, package-audit.js, package-lock.json, package-test.js, package.json, src/core/store/external/actions.js, src/modules/network/components/NetworkSwitch.vue, src/views/TheWalletView.vue
* \[x] Link to release: https://github.com/MyEtherWallet/MyEtherWallet/releases/tag/v6.6.10-hotfix.1
=> devop: 🔧 change matic api endpoint

changelog/fix-4338.md, package-lock.json, package.json, src/views/components-default/HomeFeaturesSwap.vue
=> Fix: USDT value 0 on landing page

changelog/fix-4371.md, src/modules/access-wallet/ModuleAccessWalletHardware.vue, src/modules/access-wallet/hardware/handlers/hardwares/trezor/index.js, src/modules/balance/ModuleBalanceCard.vue
=> Fix: 'Address verified' message displaying without verifying on Trezor

changelog/devop-4367.md, src/modules/balance/ModuleBalance.vue, src/modules/balance/ModuleBalanceLoader.vue
- update dashboard placeholder
=> devop: update dashboard placeholder

changelog/fix-4397.md, package-test.js, package.json, src/modules/send/ModuleSend.vue
- fix input height on send page
=> fix: fix input height on send page

CHANGELOG.md, package-lock.json, package.json
* \[x] Link to release: https://github.com/MyEtherWallet/MyEtherWallet/releases/tag/v6.6.12-hotfix.2
=> release: 🔥 v6.6.12-hotfix.2

src/modules/balance/ModuleTokensValue.vue
=> Fix: buy sell event

changelog/ui-4465.md, package-lock.json, package-test.js, package.json, src/modules/buy-sell/components/BuyComponent.vue
=> ui: 🎨 buy/sell module alignment

changelog/fix-4469.md, src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
=> Fix: Clear button not clearing extra word

builds/defaultConfig.js, changelog/fix-4470.md, connections.js, package-lock.json, package.json
=> Fix: Broken image in Intercom popup

package-test.js
=> fix: 🐛 staging build

changelog/fix-4474.md, package-lock.json, package.json, src/views/components-default/HomeWhyMew.vue
=> Fix: mobile links on landing page

changelog/fix-4478.md, package-lock.json, package.json, src/modules/contract/ModuleContractInteract.vue
=> Fix: Contract unknown function

package-lock.json, package-test.js, package.json
=> devop: 🔧 update package

changelog/ui-4522.md, package-lock.json, package.json, src/translations/careers/en_US.json
=> fix: 🐛 capitalization

changelog/ui-4520.md, package-lock.json, package.json, src/modules/transfer-history/ModuleTransferHistory.vue
=> chore: 👷 change tx history to send history

changelog/ui-4521.md, package-lock.json, package.json, src/modules/notifications/ModuleNotifications.vue
=> ui: 🎨 remove search in notification selector

changelog/ui-4473.md, package-lock.json, package.json, src/modules/swap/ModuleSwap.vue
=> Ui: Padding on swap page mobile view 

changelog/devop-4523.md, package-lock.json, package.json, src/modules/balance/ModuleBalanceCard.vue
=> devop: 🔧 hide refresh on offline build

changelog/fix-4545.md, package-lock.json, src/core/components/TheWrapperWallet.vue, src/modules/balance/ModuleTokensValue.vue
=> fix: 🐛 remove collapsible

changelog/fix-4553.md, src/modules/buy-sell/components/TokenSelect.vue
=> fix: 🐛 out of synch web3 instance

changelog/fix-4554.md, src/modules/buy-sell/components/SellComponent.vue
=> fix: 🐛 balance format

changelog/devop-4560.md, changelog/fix-4564.md, package-lock.json, src/modules/access-wallet/ModuleAccessWalletSoftware.vue
=> fix: offline build

changelog/fix-4567.md, package-lock.json, package.json
=> fix: build

changelog/fix-4573.md, package-audit.js, package-lock.json, src/modules/access-wallet/software/handlers/pathHelper.js, src/modules/dapps-center/ModuleDappsCenter.vue, src/utils/networks/nodes/index.js, tests/unit/__mocks__/networksMock.js
=> fix: node switch issue

CHANGELOG.md, builds/liveConfig.js, builds/offlineConfig.js, package-lock.json, package.json, src/dapps/staked-dapp/components/StakedStatus.vue, src/dapps/staked-dapp/metainfo.js, src/modules/dapps-center/ModuleDappsCenter.vue
* \[x] Link to release: https://github.com/MyEtherWallet/MyEtherWallet/releases/v6.7.0-hotfix.1
=> release: 🔥 v6.7.0-hotfix.1

changelog/fix-4589.md, src/core/components/AppCarousel.vue
=> fix: new tab for hardware wallet ad

changelog/fix-4601.md, src/dapps/staked-dapp/components/StakedStatus.vue
=> fix: exited status

CHANGELOG.md, package-lock.json, package.json, src/dapps/staked-dapp/metainfo.js, src/modules/dapps-center/ModuleDappsCenter.vue
* \[x] Link to release: https://github.com/MyEtherWallet/MyEtherWallet/releases/tag/v6.7.1-hotfix.1
=> release: 🔥 v6.7.1-hotfix.1

changelog/devop-4609.md, src/main/mainApp.vue, src/utils/web3-provider/methods/eth_sendTransaction.js
=> fix: matomo labels

changelog/devop-4610.md, public/manifest.json
=> chore: update manifest with the right image paths

changelog/devop-4637.md, jest.config.js, package-lock.json, src/dapps/ens-manager-dapp/TheENSManagerLayout.vue, src/modules/access-wallet/hybrid/handlers/WalletConnect/index.js, src/modules/name-resolver/resolvers/uns.js
=> chore: more cleanup

changelog/devop-4654.md, connections.js, src/utils/networks/nodes/xdcnetwork-ws.js, src/utils/web3-provider/providers/ws-provider.js, src/utils/web3-provider/providers/ws-web3-provider.js, src/utils/web3-provider/providers/xdc-parser.js
=> devop: handle xdc address

changelog/devop-4655.md, src/core/helpers/unit.js, src/modules/swap/ModuleSwapRates.vue, src/modules/swap/handlers/providers/changelly.js
=> devop: replace changelly api

changelog/devop-4669.md, src/modules/swap/handlers/providers/changelly.js
=> devop: add network fee deduction

changelog/fix-4668.md, src/modules/access-wallet/hardware/handlers/hardwares/ledger/index.js
=> fix: ledger token sign

changelog/devop-4670.md, package-test.js
=> chore: exclude package, add changelog

changelog/devop-4677.md, connections.js, package-lock.json, package.json
=> devop: add myetherwallet to connections

changelog/fix-4679.md, src/views/TheWalletView.vue
=> fix: add web3 subscription catch

changelog/devop-4691.md, package-lock.json, src/views/components-default/TheDefaultFooter.vue
=> devop: move bug bounty

changelog/fix-4692.md, src/modules/swap/ModuleSwapRates.vue, src/views/components-default/TheDefaultFooter.vue, src/views/layouts-wallet/TheDashboardLayout.vue
=> fix: bug bounty links outside wallet

README.md, changelog/devop-4693.md
=> devop: update readme

builds/liveConfig.js, changelog/fix-4696.md, package-lock.json, src/modules/swap/ModuleSwap.vue, src/modules/swap/handlers/handlerSwap.js, src/modules/swap/handlers/providers/changelly.js
=> fix: swap and workbox changes

CHANGELOG.md, builds/liveConfig.js, fetchLists/index.js, package-lock.json, package.json, src/modules/swap/handlers/providers/changelly.js
* \[x] Link to release: https://github.com/MyEtherWallet/MyEtherWallet/releases/tag/v6.7.6-hotfix.1
=> release: 🔥 release v6.7.6-hotfix.1

builds/defaultConfig.js, builds/liveConfig.js, changelog/devop-4702.md, src/core/plugins/registerServiceWorker.js
=> chore: add kosala's changes

.github/workflows/add-to-mewbuilds.yml, changelog/devop-4703.md, src/core/plugins/registerServiceWorker.js, src/modules/network/components/NetworkSwitch.vue
=> devop: remove bsc

CHANGELOG.md, changelog/fix-4705.md, package-lock.json, package.json, src/modules/access-wallet/ModuleAccessWalletMobile.vue, src/modules/access-wallet/hybrid/handlers/WalletConnect/index.js
* \[x] Link to release: https://github.com/MyEtherWallet/MyEtherWallet/releases/tag/v6.7.6-hotfix.2
=> release: 🔥 v6.7.6-hotfix.2

changelog/devop-4706.md, fetchLists/index.js, package-lock.json, src/modules/access-wallet/ModuleAccessWalletMobile.vue, src/modules/swap/ModuleSwap.vue, src/modules/swap/handlers/handlerSwap.js
=> devop: cleanup for release

changelog/fix-4722.md, package-lock.json, src/core/helpers/gasPriceHelper.js, src/modules/buy-sell/ModuleBuySell.vue, src/modules/buy-sell/components/BuyComponent.vue, src/modules/buy-sell/components/SellComponent.vue, src/modules/buy-sell/components/TokenSelect.vue, src/modules/swap/handlers/providers/mew-provider-class.js
=> fix: cleanup BSC references, fix swap

CHANGELOG.md
=> chore: text change

changelog/feature-4782.md, src/assets/images/networks/aa.svg, src/utils/networks/nodes/arthera-ws.js, src/utils/networks/nodes/index.js, src/utils/networks/types/AA.js, src/utils/networks/types/index.js
* \[x] Is this a user submitted feature request?
* \[x] Link to issue: https://github.com/MyEtherWallet/MyEtherWallet/issues/4738
* \[ ] Add test cases or procedure
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205760308201046
=> Feature: add arthera

changelog/devop-4787.md, package-lock.json, package.json, public/index.html, src/views/components-wallet/TheWrapperWallet.vue
=> devop: remove coinzilla

changelog/devop-4793.md, package-lock.json, package.json, src/views/TheWalletView.vue, src/views/components-default/NewLookBanner.vue, src/views/components-default/TheDefaultHeader.vue, src/views/components-default/TheMobileMenu.vue
=> devop: update header transparency, switch logo

changelog/fix-4796.md, src/views/layouts-default/TheToolsLayout.vue
=> fix: tools link

changelog/fix-4811.md, package-lock.json, package.json, src/views/components-wallet/TheWrapperWallet.vue
=> devop: disable nft for now

changelog/devop-4823.md, package-audit.js, package-lock.json, package.json, src/apollo/queries/wallets/wallets.graphql, src/apollo/schemas/api.json, src/core/mixins/handlerWallet.mixin.js, src/core/store/external/actions.js, src/core/store/external/getters.js, src/core/store/external/mutations.js, src/core/store/external/state.js, src/dapps/aave-dapp/metainfo.js, src/dapps/coinbase-staking/TheCoinbaseStakingLayout.vue, src/dapps/coinbase-staking/components/CoinbaseStakingSummary.vue, src/dapps/coinbase-staking/metainfo.js, src/dapps/coinbase-staking/modules/ModuleCoinbaseStaking.vue, src/dapps/coinbase-staking/modules/ModuleCoinbaseUnstaking.vue, src/dapps/ens-manager-dapp/metainfo.js, src/dapps/eth-blocks/metainfo.js, src/dapps/flyover-dapp/components/pegout/AcceptQuote.vue, src/dapps/flyover-dapp/metainfo.js, src/dapps/rns-manager-dapp/metainfo.js, src/dapps/staked-dapp/metainfo.js, src/dapps/stakewise/metainfo.js, src/dapps/unstoppable-domains-dapp/metainfo.js, src/modules/confirmation/ModuleConfirmation.vue, src/modules/dapps-center/ModuleDappsCenter.vue, src/utils/networks/types/ROOTSTOCK.js
=> devop: copy changes

src/views/layouts-default/TheCareersLayout.vue, src/views/layouts-default/TheCompanyLayout.vue, src/views/layouts-default/TheTeamLayout.vue, src/views/layouts-default/TheToolsLayout.vue
=> chore: cleanup

CHANGELOG.md, src/dapps/TheWrapperDapp.vue, src/modules/access-wallet/hardware/components/AccessWalletPaths.vue, src/modules/dapps-center/ModuleDappsCenter.vue, src/modules/staking/ModuleStakingCenter.vue
* \[ ] Is this a user submitted feature request?
* \[ ] Add test cases or procedure
* \[ ] Merged changelog generation branch
* \[ ] Created a release
* \[ ] Link to release:
* \[ ] Updated package.json version
=> chore: fix some comments

CHANGELOG.md, changelog/fix-4902.md, package-lock.json, package.json, src/views/components-default/TheDefaultFooter.vue
=> devop: add version

changelog/devop-4934.md, connections.js, src/modules/access-wallet/hardware/handlers/hardwares/ledger/appPaths.js, src/modules/name-resolver/index.js, src/utils/networks/nodes/index.js, src/utils/networks/nodes/rootstock-testnet-ws.js, src/utils/networks/tlds/ROOTSTOCKTESTNET.js, src/utils/networks/tlds/index.js, src/utils/networks/types/ROOTSTOCKTESTNET.js, src/utils/networks/types/index.js
This PR adds `Rootstock Testnet` network integration to MyEtherWallet.
* Create or Import wallet with `Rootstock` is working
* Send / Receive `RBTC` and ERC20 tokens flow working
* Ledger connection and signing with `Rootstock` is working
* Rootstock name resolution is working
* Checkout to the branch in this PR
* `npm run dev` or `npm run juststart`
* Now select `Rootstock Testnet` option to test items mentioned in the description section
=> Devop: Rootstock Testnet integration

changelog/fix-4956.md, src/modules/swap/ModuleSwap.vue
=> fix: swap not clearing

builds/liveConfig.js, changelog/devop-4954.md, package-lock.json, package.json, src/modules/send-offline/ModuleSendOffline.vue, src/modules/tools/ModuleToolsOfflineHelper.vue
=> fix: use toBase

.vscode/settings.json, package.json, pnpm-lock.yaml, src/stores/configs.ts, src/stores/popup.ts, tsconfig.app.json, tsconfig.json
* \[ ] Is this a user submitted feature request?
* \[ ] Add test cases or procedure
=> chore: v7 popup store

package.json
Specify minimum NodeJS and pnpm versions in package.json
=> chore: specify package.json pnpm and nodejs engines

.github/workflows/add-to-mewbuilds.yml, CHANGELOG.md, changelog/fix-5066.md, package-test.js, package.json, src/core/helpers/detectProvider.js, src/main/mainApp.vue
=> fix: eip feat when phantom is installed

src/utils/networks/nodes/rootstock-ws.js
=> devop: update rsk

changelog/fix-5131.md, package.json, src/core/store/external/getters.js, src/modules/confirmation/components/ConfirmationSendTransactionDetails.vue
=> fix: issue where currency doesn't show up when it's too low

builds/liveConfig.js, changelog/feat-5162.md, package-test.js, package.json, public/privacy-policy-android.html
=> feat: add privacy policy

src/components/AppViewAsDialog.vue, src/modules/crypto/ModuleTokenInfo.vue, src/modules/crypto/components/token_info/TokenInfoBalance.vue
* \[ ] Is this a user submitted feature request?
* \[ ] Add test cases or procedure
* \[ ] Merged changelog generation branch
* \[ ] Created a release
* \[ ] Link to release:
* \[ ] Updated package.json version
=> fix: 🐛 comments
