MyEtherWallet/MyEtherWallet

src/wallets/web3-provider/methods/eth_sendTransaction.js, src/wallets/web3-provider/methods/eth_signTransaction.js, src/wallets/web3-provider/methods/utils.js
=> fix invalid chain id error

CHANGELOG.md, package-lock.json, src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue, src/networks/nodes/eth-mew-ws.js, src/networks/nodes/index.js, vue.config.js
=> Add MEW Websocket node

src/networks/nodes/poa.js
Relates to https://github.com/MyEtherWallet/MyEtherWallet/issues/762
Replace Infura endpoint with core.poa.network for Core POA Network due to [Infura’s POA Core nodes has been disabled on 2/1/19](https://forum.poa.network/t/infuras-poa-core-nodes-to-be-disabled-on-2-1-19/1881)
=> Replace Infura endpoint with core.poa.network for Core POA Network

src/translations/errors-secalot/en_US.json, src/translations/errors-secalot/es_ES.json, src/translations/errors-secalot/ja_JP.json, src/translations/errors-secalot/ko_KR.json, src/translations/errors-secalot/ru_RU.json, src/translations/errors-secalot/zh_CN.json, src/wallets/hardware/secalot/errorHandler.js, src/wallets/hardware/secalot/secalotUsb.js
With this change, Secalot will work on all Chrome versions, old and new.
A firmware update to version 4 is required. It can be downloaded from (https://www.secalot.com/downloads/).
If Secalot runs an old firmware, it will be detected and a toast with a suggestion to update will be shown.
I've also updated some Secalot related error messages to be shown as toasts.
=> Chrome 72 compatibility for Secalot.

src/wallets/hardware/secalot/secalotEth.js
In the pull request from yesterday, a check for Secalot's firmware version was added. If the version is less than 4, a pin code check is still performed and then an error message to update to version 4 or later is displayed. With that, if a user enters a wrong pin into the form and presses "Unlock wallet" repeatedly, the wallet will be wiped because of the wrong pin, but the user would not know about that, as the error messages say "incorrect version".
This commit fixes this.
=> Enhance Secalot’s firmware version detection

src/wallets/bip44/ledgerPaths.js, src/wallets/bip44/paths.js
It appears that an ETC path used in [mew vintage](https://github.com/kvhnuke/etherwallet/blob/385cf62a3aa1960f8c43e768e00b250d1e8959fb/app/scripts/controllers/decryptWalletCtrl.js#L29) is slightly different than the path used on the [current mew](https://github.com/MyEtherWallet/MyEtherWallet/blob/b7f815823813de78c98ba8c01ecf8ecd54809ca0/src/wallets/bip44/paths.js#L94).
=> add ethereum classic path as presented in mew v3  [5.0.8]

src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.vue
-fixes user not getting redirected to access-wallet page after creating a json file or mnemonic phrase wallet.
=> fix success modal not linking to unlock wallet page [5.0.8]

src/wallets/hardware/secalot/secalotEth.js
With MEW v5.0.14, ethereumjs-tx was updated from version 1.3.7 to version 2.0.0. With this update, an exception is unconditionally thrown in SecalotEth.prototype.signTransaction when raw data that is to be signed by the hardware device is constructed. SecalotEth.js, line 155, eTx.v = chainID;. Ethereumjs-tx 2.0.0 introduced a check that when a new "v" is assigned to a transaction, it should be compatible with EIP155 (v=chainID*2 + 35 or + 36). Here raw data to be signed was constructed (v=checkID, s=0, r=0), so this check was failing.
This pull request fixes the issue.
=> An exception is thrown when signing transactions with Secalot

src/wallets/hardware/bitbox/digitalBitboxEth.js, src/wallets/hardware/bitbox/digitalBitboxUsb.js
Increases timeout to 35 seconds for Windows users instead of polling
every 3 seconds since Windows 10 1903+ waits for user confirmation
- Fixes U2F hijack issue for new Windows 10 update 1903 by waiting 35 seconds (to accommodate 30 second firmware timeout) instead of polling every 3 seconds. Windows < 10, MacOS and Linux are not affected, this is a Windows 10 only fix. 
- Windows 10 users pre-1903 update may have to wait up to 25 seconds if they do not sign a transaction within 3 seconds. 
- Fix tested on newest Chrome on Windows 10 1903, Windows 10 1803, Ubuntu 18.04 and MacOS
@SteveMieskoski 
- There is an associated firmware patch release v7.0.1 here: https://github.com/digitalbitbox/mcu/releases/tag/v7.0.1 that can be loaded via the `load_firmware.py` script for testing
- **The …
=> bitbox-windows: fix u2f timeout for windows users

src/partners/kyber/config/currenciesETH.js, src/partners/partnersConfig/EthereumTokens.js
The LRC token was upgraded to a new version on May 7th, 2019. The new token's address is 0xBBbbCA6A901c926F240b89EacB641d8Aec7AEafD (lrctoken.eth). For more information please see: https://medium.com/loopring-protocol/lrc-token-upgraded-a26ee6f87b84
=> Update LRC token Information

src/wallets/hardware/bitbox/digitalBitboxEth.js
Introduce a minimum supported version and a maximum supported version.
@SteveMieskoski 
Our previous semver checking was too restrictive for users with newer firmware and non-breaking changes.
This enables users to use MEW with the new 7.0.3 bitbox firmware release
=> bitbox: update semantic versioning to be less restrictive

CHANGELOG.md, src/workers/wallet.worker.js
- correct wrong property path for config object in wallet.worker.js
=> fix config property paths in wallet worker

src/networks/types/ERE.js
Our explorer https://explorer.ethercore.org address route has been changed.
Please have a look at https://github.com/MyEtherWallet/ethereum-lists/pull/1398 also.
=> Change EtherCore explorer address

src/layouts/InterfaceLayout/components/InterfaceAddress/InterfaceAddress.vue
Because clicking on it causes the error "Wallet type wallet_connect can't switch addresses"
* \[ ] Updated CHANGELOG.md
=> Hide switch address if logged in via WalletConnect

src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
This fixes oveflow of the balance string in the access mnemonic phrase table
=> fix: format balance string in address

changelog/fix-3436.md, package-lock.json, src/modules/settings/components/SettingsGasPrice.vue
=> fix: 🐛 only allow numbers on gas price input

src/wallets/hardware/bitbox/digitalBitboxUsb.js
WebHID access to the BitBox01 stopped working as of Chrome version
97 due to incorrect vendor/product filter names. See also:
digitalbitbox/bitbox02-api-js#62
The same issue was fixed for the BitBox02 previously here:
https://github.com/MyEtherWallet/MyEtherWallet/issues/3618
=> bitbox01: fix WebHID filters to restore access in Chrome 97+

changelog/fix-4245.md, package.json, src/modules/address-book/components/AddressBookAddEdit.vue
- replace text button with mew-button
=> fix: replace remove address button with mew-button

changelog/fix-4368.md, src/modules/settings/components/SettingsAddressTable.vue
- add tooltip to show full address on settings address table
=> fix: add tooltip to show full address on address table

changelog/fix-4541.md, src/core/helpers/addressUtils.js
* \[X] Added entry to ./changelog
The `return` statement is missing on `toChecksumAdd` call due to which address resolution is not working. Just fixed this bug by adding `return`. 
Very small pull request. Need to merge @gamalielhere
=> fix: 🐛 return to checksum address value
